<?xml version="1.0" encoding="UTF-8" ?>
<!--外部dtd-->
<!DOCTYPE students SYSTEM "student.dtd">

<!--内部dtd-->
<!--<!DOCTYPE students [-->
<!--        <!ELEMENT students (student+) >-->
<!--        <!ELEMENT student (name,age,sex)>-->
<!--        <!ELEMENT name (#PCDATA)>-->
<!--        <!ELEMENT age (#PCDATA)>-->
<!--        <!ELEMENT sex (#PCDATA)>-->
<!--        <!ATTLIST student number ID #REQUIRED>-->
<!--        ]>-->

<students>
    <student number="itcast_0001">
        <name>tom</name>
        <age>18</age>
        <sex>male</sex>
    </student>
</students>